### ISSUE TITLE
Issues with trafaret dependency

### ISSUE THREAD

**Issue by bnouvelbmll** [rambler-digital-solutions/airflow-declarative#41]
To be able to use airflow-declarative with `python 3.7`.
I had to `pip install trafaret==1.2.0` and to initialise with the following:

```
import trafaret
trafaret.Email=trafaret.String
import airflow_declarative
```

Otherwise, I have an error that "Email" requires a positional argument `val`..
The main issue seems to be with trafaret, but it may be simpler to validate simply "string".

**Comment by bnouvelbmll** [comment]
Actually I am bit confused with dependency. I am bit confused with 'trafaret' version required.
When I use '2.0(alpha?)' I end up with the following error:
'''
'Dict' object has no attribute 'make_optional'
'''

When I use 1.2.0, this is the following error

~/miniconda3/lib/python3.7/site-packages/airflow_declarative/schema.py in ensure_schema(schema)
     67     :rtype: dict
     68     """
---> 69     return SCHEMA.check_and_return(schema)
     70 
     71 

AttributeError: 'Dict' object has no attribute 'check_and_return'


What is meant to be the right version of trafaret ?

**Comment by kxepal** [comment]
Hi! For current release the right versions are:
```
trafaret==0.10.4
trafaret-config==1.0.1
```

Suddenly, they were not pinned in time so it becomes eventually broken. Sorry for that! This is already fixed in master and the new release will happen on this weekends. Stay tuned!

**Comment by KostyaEsmukov** [comment]
The latest version in pypi is probably broken anyways, so I'd suggest to install right from the current master branch until the new one is released on pypi:

```
pip install 'git+https://github.com/rambler-digital-solutions/airflow-declarative.git'
```

**Comment by bnouvelbmll** [comment]
Thanks,  I managed to get it working from pip so I have not tried latest.

I thought I may be also share what I am doing with your project, as I think it could be a nice "contrib" to your project.  Basically, instead of scanning a directory as in the README, I am scanning kubernetes for configmaps  tagged with a specific label. This allows DAG to be seen as resources on kubernetes. The next step could be to have custom CRDs - but at for the moment it does not seem fully necessary.
'''
# airflow DAG  - keep this comment as these words are useful to make airflow "safe discovery" happy

# the next block below is  "hack" currently required to have airflow_declarative working
# from pip  and we should be able to replace it by a single import statement once pip is fixed
import trafaret
trafaret.Email=trafaret.String  
from airflow_declarative import schema    
from airflow_declarative import builder
from airflow_declarative import transformer
schema.ensure_schema=builder.ensure_schema=transformer.ensure_schema=lambda x:x
import airflow_declarative

import tempfile
import time
import os
import yaml

import kubernetes.client
from kubernetes.client.rest import ApiException
from kubernetes import config as kubeconfig
import kubernetes

if 'KUBERNETES_PORT' in os.environ:
    kubeconfig.load_incluster_config()
else:
    kubeconfig.load_kube_config()

client = kubernetes.client
namespace=os.environ.get("KUBERNETES_NAMESPACE", "default")
cfg = client.Configuration()
api_instance = client.CoreV1Api(kubernetes.client.api_client.ApiClient(cfg))
limit = 100
dags=[]                                                                                                                                                                         
api_response = api_instance.list_namespaced_config_map(namespace, pretty='false',label_selector='configmap_type=airflow-dag', limit=limit)
for item in api_response.items:
    with tempfile.NamedTemporaryFile(mode="w+",suffix=".yaml") as f:
       f.write(item.data["dag.yaml"])                                                                                                                 
       dag=airflow_declarative.from_path(f.name)  
       dags.append(dag)                                                                                                                                                                
                                                                                                                                                                                
globals().update({dag.dag_id: dag for dl in dags for dag in dl})
'''

**Comment by kxepal** [comment]
And finally this issue is solved. Please upgrade to 1.1 version. Sorry for waiting for so long!
