### ISSUE TITLE
dict type does not have check_and_return method

### ISSUE THREAD

**Issue by chandan-u** [rambler-digital-solutions/airflow-declarative#6]
def ensure_schema(schema):
    """Ensures that schema is valid."""

    :param dict schema: Airflow DAGs schema.
    :returns: Airflow DAGs schema.
    :rtype: dict
    """
    return SCHEMA.check_and_return(schema)

# The schema object does not have  the check_and_return method declared. Please help?

**Comment by kxepal** [comment]
Which version of trafaret / trafaret_config do you have?

**Comment by chandan-u** [comment]
Hi kxepal ,

I am using the following version of trafaret and python 3.6.4
trafaret==2.0.0a1
trafaret-config==1.0.1

**Comment by kxepal** [comment]
@chandan-u This issue should be fixed in #8. Please, reopen issue if it will remains on master. We'll make release quite soon.
